name: ecommerceflutter
description: "ecommerce with Flutter"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.9.0
  glassmorphism: ^3.0.0
  flutter_localization: ^0.3.2
  connectivity_plus: ^6.1.4
  flutter_appauth: ^9.0.0
  uni_links: ^0.5.1
  flutter_neumorphic: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15 
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
      - assets/images/
