import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../viewmodels/language_vm.dart';

const Map<String, Map<String, String>> _translations = {
  'en': {
    'about': 'About',
    'orders': 'Orders',
    'products': 'Products',
    'searchHint': 'Search products...',
    'cat_all': 'All',
    'cat_food': 'Food',
    'cat_technology': 'Technology',
    'cat_hygiene': 'Hygiene Products',
    'allProducts': 'All Products',
    'recentProducts': 'Recent Products',
    'recentDiscounted': 'Recent Discounted Products',
    'discounted': 'Discounted Products',
    'logout': 'Logout',
    'addToCart': 'Add to Cart',
    'cart': 'Cart',
    'orderConfirmation': 'Confirm Order',
    'orderConfirmed': 'Your order has been confirmed!',
    'emptyCart': 'Your cart is empty',
    'checkout': 'Checkout',
    'viewCart': 'View Cart',
    'quantity': 'Quantity',
    'viewDetail': 'View Details',
    'total': 'total',
    'stock': 'Stock',
    'deleteConfirmationTitle': 'Delete Confirmation',
    'deleteConfirmationContent': 'Are you sure you want to delete?',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'noInternet': 'No internet',
    'Confirm': 'Confirm',
    'backToHome': 'Back to Home',
    'aboutUsShortText': 'E-commerce for you, always.',
    'sonSiparisler': 'Son Siparişler',
    'Hakkımızda': 'Hakkımızda',
    "nav_orders": "Orders",
    "nav_products": "Products",
    "nav_about": "About",
    "noData": "No data",
    "discount": "Discount",
    'noProductsFound': 'No products found',
    'noDiscountedProductsFound': 'No discounted products found',
    'loading': 'Loading...',
    'errorOccurred': 'An error occurred',
    'checkingConnection': 'Checking connection...',
    'connectionError': 'Connection error',
    'checkInternetConnection': 'Please check your internet connection',
    'confirm': 'Confirm',
    'loadingStock': 'Loading stock info...',
    'loadingImage': 'Loading image...',
    'imageLoadError': 'Could not load image',
    'noImage': 'No image found',
    'productDescription': 'Product Description',
    'stockStatus': 'Stock Status',
    'inStock': 'In Stock',
    'selectQuantity': 'Select Quantity',
    'totalPrice': 'Total Price',
    'addedToCart': 'added to cart',
    'appName': 'EcommerceApp',
    'processingOrder': 'Processing order...',
    'orderSuccessMessage':
        'Your order has been successfully received and processed.',
    'orderInfo': 'Order Information',
    'orderStatus': 'Order Status:',
    'orderCompleted': 'Completed',
    'processTime': 'Process Time:',
    'editQuantity': 'Edit Quantity',
    'availableStock': 'Available Stock',
    'unit': 'pieces'
  },
  'tr': {
    'about': 'Hakkında',
    'orders': 'Siparişler',
    'products': 'Ürünler',
    'searchHint': 'Ürün ara...',
    'cat_all': 'Hepsi',
    'cat_food': 'Gıda',
    'cat_technology': 'Teknoloji',
    'cat_hygiene': 'Hijyenik Ürünler',
    'allProducts': 'Tüm Ürünler',
    'recentProducts': 'Son Eklenen Ürünler',
    'recentDiscounted': 'Son İndirimli Ürünler',
    'discounted': 'İndirimli Ürünler',
    'logout': 'Çıkış Yap',
    'addToCart': 'Sepete Ekle',
    'cart': 'Sepetiniz',
    'orderConfirmation': 'Siparişi Onayla',
    'orderConfirmed': 'Siparişiniz onaylandı!',
    'emptyCart': 'Sepetiniz boş',
    'checkout': 'Siparişi Onayla',
    'viewCart': 'Sepete Git',
    'quantity': 'Adet',
    'viewDetail': 'Detaya Git',
    'total': 'Toplam',
    'stock': 'Stok',
    'deleteConfirmationTitle': 'Silme Onayı',
    'deleteConfirmationContent': 'Silmek istediğinize emin misiniz?',
    'cancel': 'İptal',
    'delete': 'Sil',
    'noInternet': 'İnternet bağlantısı yok',
    'Confirm': 'Onayla',
    'backToHome': 'Ana sayfaya dön',
    'aboutUsShortText': 'E-ticaret her zaman sizin için.',
    'sonSiparisler': 'Recent Orders',
    'Hakkımızda': 'About Us',
    "nav_orders": "Sipariş",
    "nav_products": "Ürünler",
    "nav_about": "Bilgi",
    "noData": "Veri yok",
    "discount": "İndirim",
    'noProductsFound': 'Ürün bulunamadı',
    'noDiscountedProductsFound': 'İndirimli ürün bulunamadı',
    'loading': 'Yükleniyor...',
    'errorOccurred': 'Bir hata oluştu',
    'checkingConnection': 'Bağlantı kontrol ediliyor...',
    'connectionError': 'Bağlantı hatası',
    'checkInternetConnection': 'Lütfen internet bağlantınızı kontrol edin',
    'confirm': 'Onayla',
    'loadingStock': 'Stok bilgisi yükleniyor...',
    'loadingImage': 'Resim yükleniyor...',
    'imageLoadError': 'Resim yüklenemedi',
    'noImage': 'Resim bulunamadı',
    'productDescription': 'Ürün Açıklaması',
    'stockStatus': 'Stok Durumu',
    'inStock': 'Stokta',
    'selectQuantity': 'Miktar Seç',
    'totalPrice': 'Toplam Fiyat',
    'addedToCart': 'sepete eklendi',
    'appName': 'EcommerceApp',
    'processingOrder': 'Sipariş işleniyor...',
    'orderSuccessMessage': 'Siparişiniz başarıyla alındı ve işleme konuldu.',
    'orderInfo': 'Sipariş Bilgileri',
    'orderStatus': 'Sipariş Durumu:',
    'orderCompleted': 'Tamamlandı',
    'processTime': 'İşlem Zamanı:',
    'editQuantity': 'Miktarı Düzenle',
    'availableStock': 'Mevcut Stok',
    'unit': 'adet',
  },
  'fr': {
    'about': 'À propos de nous',
    'orders': 'Ordres',
    'products': 'Produits',
    'searchHint': 'Rechercher...',
    'cat_all': 'Tous',
    'cat_food': 'Alimentation',
    'cat_technology': 'Technologie',
    'cat_hygiene': 'Produits d’hygiène',
    'allProducts': 'Tous les produits',
    'recentProducts': 'Produits Récents',
    'recentDiscounted': 'Produits Récemment Soldés',
    'discounted': 'Produits en Promotion',
    'logout': 'Déconnexion',
    'addToCart': 'Ajouter au Panier',
    'cart': 'Panier',
    'orderConfirmation': 'Confirmer la Commande',
    'orderConfirmed': 'Votre commande est confirmée !',
    'emptyCart': 'Votre panier est vide',
    'checkout': 'Passer à la Caisse',
    'viewCart': 'Voir le Panier',
    'quantity': 'Quantité',
    'viewDetail': 'Voir Détails',
    'total': 'total',
    'stock': 'Stock',
    'deleteConfirmationTitle': 'Confirmation de suppression',
    'deleteConfirmationContent': 'Êtes-vous sûr de vouloir supprimer ?',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'noInternet': 'Pas de connexion Internet',
    'Confirm': 'Confirmer',
    'backToHome': "Retour à la page d'accueil",
    'aboutUsShortText': 'E-commerce pour vous, toujours.',
    'sonSiparisler': 'Commandes récentes',
    'Hakkımızda': 'À propos de nous',
    "nav_orders": "Commandes",
    "nav_products": "Produits",
    "nav_about": "À propos",
    "noData": "Aucune donnée",
    "discount": "Remise",
    'noProductsFound': 'Aucun produit trouvé',
    'noDiscountedProductsFound': 'Aucun produit à prix réduit trouvé',
    'loading': 'Chargement...',
    'errorOccurred': "Une erreur s'est produite",
    'checkingConnection': 'Vérification de la connexion...',
    'connectionError': 'Erreur de connexion',
    'checkInternetConnection': 'Veuillez vérifier votre connexion Internet',
    'confirm': 'Confirmer',
    "loadingStock": "Chargement des informations de stock...",
    "loadingImage": "Chargement de l'image...",
    "imageLoadError": "Impossible de charger l'image",
    "noImage": "Aucune image trouvée",
    "productDescription": "Description du produit",
    "stockStatus": "État du stock",
    "inStock": "En stock",
    "selectQuantity": "Sélectionner la quantité",
    "totalPrice": "Prix total",
    "addedToCart": "ajouté au panier",
    "appName": "EcommerceApp",
    "processingOrder": "Traitement de la commande...",
    "orderSuccessMessage": "Votre commande a été reçue et traitée avec succès.",
    "orderInfo": "Informations sur la commande",
    "orderStatus": "Statut de la commande :",
    "orderCompleted": "Terminée",
    "processTime": "Temps de traitement :",
    "editQuantity": "Modifier la quantité",
    "availableStock": "Stock disponible",
    "unit": "pièces",
  },
  'it': {
    'about': 'Chi siamo',
    'orders': 'Ordini',
    'products': 'Prodotti',
    'searchHint': 'Cerca prodotti...',
    'cat_all': 'Tutti',
    'cat_food': 'Cibo',
    'cat_technology': 'Tecnologia',
    'cat_hygiene': 'Prodotti per l\'igiene',
    'allProducts': 'Tutti i prodotti',
    'recentProducts': 'Prodotti Recenti',
    'recentDiscounted': 'Prodotti Scontati Recenti',
    'discounted': 'Prodotti in Sconto',
    'logout': 'Esci',
    'addToCart': 'Aggiungi al Carrello',
    'cart': 'Carrello',
    'orderConfirmation': 'Conferma Ordine',
    'orderConfirmed': 'Il tuo ordine è confermato!',
    'emptyCart': 'Il tuo carrello è vuoto',
    'checkout': 'Procedi all\'Acquisto',
    'viewCart': 'Visualizza Carrello',
    'quantity': 'Quantità',
    'viewDetail': 'Vedi Dettagli',
    'total': 'totale',
    'stock': 'Stock',
    'deleteConfirmationTitle': "Conferma dell'eliminazione",
    'deleteConfirmationContent': 'Sei sicuro di voler eliminare?',
    'cancel': 'Cancellare',
    'delete': 'Eliminare',
    'noInternet': 'Nessuna connessione internet',
    'Confirm': 'Confermare',
    'backToHome': "Torna alla home page",
    'aboutUsShortText': 'E-commerce per te, sempre.',
    'sonSiparisler': 'Ordini recenti',
    'Hakkımızda': 'Chi siamo',
    "nav_orders": "Ordini",
    "nav_products": "Prodotti",
    "nav_about": "Informazioni",
    "noData": "Nessun dato",
    "discount": "Sconto",
    'noProductsFound': 'Nessun prodotto trovato',
    'noDiscountedProductsFound': 'Nessun prodotto scontato trovato',
    'loading': 'Caricamento...',
    'errorOccurred': 'Si è verificato un errore',
    'checkingConnection': 'Controllo della connessione...',
    'connectionError': 'Errore di connessione',
    'checkInternetConnection':
        'Si prega di controllare la connessione Internet',
    'confirm': 'Confermare',
    "loadingStock": "Caricamento delle informazioni di magazzino...",
    "loadingImage": "Caricamento dell'immagine...",
    "imageLoadError": "Impossibile caricare l'immagine",
    "noImage": "Nessuna immagine trovata",
    "productDescription": "Descrizione del prodotto",
    "stockStatus": "Stato del magazzino",
    "inStock": "Disponibile",
    "selectQuantity": "Seleziona quantità",
    "totalPrice": "Prezzo totale",
    "addedToCart": "aggiunto al carrello",
    "appName": "EcommerceApp",
    "processingOrder": "Elaborazione dell'ordine...",
    "orderSuccessMessage":
        "Il tuo ordine è stato ricevuto ed elaborato con successo.",
    "orderInfo": "Informazioni sull'ordine",
    "orderStatus": "Stato dell'ordine:",
    "orderCompleted": "Completato",
    "processTime": "Tempo di elaborazione:",
    "editQuantity": "Modifica quantità",
    "availableStock": "Stock disponibile",
    "unit": "pezzi",
  },
  'de': {
    'about': 'Über uns',
    'orders': 'Bestellungen',
    'products': 'Produkte',
    'searchHint': 'Produkte suchen...',
    'cat_all': 'Alle',
    'cat_food': 'Lebensmittel',
    'cat_technology': 'Technologie',
    'cat_hygiene': 'Hygieneprodukte',
    'allProducts': 'Alle Produkte',
    'recentProducts': 'Neueste Produkte',
    'recentDiscounted': 'Kürzlich Reduzierte Produkte',
    'discounted': 'Reduzierte Produkte',
    'logout': 'Abmelden',
    'addToCart': 'In den Warenkorb',
    'cart': 'Warenkorb',
    'orderConfirmation': 'Bestellung Bestätigen',
    'orderConfirmed': 'Ihre Bestellung wurde bestätigt!',
    'emptyCart': 'Ihr Warenkorb ist leer',
    'checkout': 'Zur Kasse',
    'viewCart': 'Warenkorb Anzeigen',
    'quantity': 'Menge',
    'viewDetail': 'Details Anzeigen',
    'total': 'Gesamt',
    'stock': 'Bestand',
    'deleteConfirmationTitle': 'Bestätigung der Löschung',
    'deleteConfirmationContent': 'Möchten Sie wirklich löschen?',
    'cancel': 'Stornieren',
    'delete': 'Löschen',
    'noInternet': 'Keine Internetverbindung',
    'Confirm': 'Bestätigen',
    'backToHome': "Zurück zur Startseite",
    'aboutUsShortText': 'E-Commerce für Sie, immer.',
    'sonSiparisler': 'Letzte Bestellungen',
    'Hakkımızda': 'Über uns',
    "nav_orders": "Bestellungen",
    "nav_products": "Produkte",
    "nav_about": "Über uns",
    "noData": "Keine Daten",
    "discount": "Rabatt",
    'noProductsFound': 'Kein Produkt gefunden',
    'noDiscountedProductsFound': 'Keine reduzierten Produkte gefunden',
    'loading': 'Laden...',
    'errorOccurred': 'Ein Fehler ist aufgetreten',
    'checkingConnection': 'Verbindung wird geprüft...',
    'connectionError': 'Verbindungsfehler',
    'checkInternetConnection': 'Bitte überprüfen Sie Ihre Internetverbindung',
    'confirm': 'Bestätigen',
    "loadingStock": "Lade Lagerinformationen...",
    "loadingImage": "Bild wird geladen...",
    "imageLoadError": "Bild konnte nicht geladen werden",
    "noImage": "Kein Bild gefunden",
    "productDescription": "Produktbeschreibung",
    "stockStatus": "Lagerstatus",
    "inStock": "Auf Lager",
    "selectQuantity": "Menge auswählen",
    "totalPrice": "Gesamtpreis",
    "addedToCart": "zum Warenkorb hinzugefügt",
    "appName": "EcommerceApp",
    "processingOrder": "Bestellung wird verarbeitet...",
    "orderSuccessMessage":
        "Ihre Bestellung wurde erfolgreich empfangen und bearbeitet.",
    "orderInfo": "Bestellinformationen",
    "orderStatus": "Bestellstatus:",
    "orderCompleted": "Abgeschlossen",
    "processTime": "Bearbeitungszeit:",
    "editQuantity": "Menge bearbeiten",
    "availableStock": "Verfügbarer Bestand",
    "unit": "Stück",
  },
};

String t(WidgetRef ref, String key) {
  final lang = ref.watch(languageProvider);
  return _translations[lang]?[key] ?? key;
}
